#!/usr/bin/env bash
# Clean up state created during demo / testing sessions.
#
# What this script DOES NOT touch (safe):
#   - Source code, configs, docs
#   - Base MySQL data: real users (1..1000), orders not tagged demo, activity_logs
#   - Encrypted ssn/credit_card (rebuilding the keystore != cleanup)
#   - Acra keystore + .env (keep so the chain still works next session)
#
# What gets cleaned depends on the flag(s):
#   (default)       : __pycache__, the Flask demo if still running
#   --demo-data     : also delete demo rows: orders 'rw-demo-%' + secure_cards test row
#                     + HA cluster's ha_demo table + self-seeded demo users (id<=5 in HA)
#   --logs          : also truncate logs/mysql (general.log, slow.log) - the 40+MB drag
#   --ha            : also tear down the HA cluster + ha-router (frees ~1.5GB RAM)
#   --all           : everything above
#   --help          : print this list and exit
#
# Run from project root:
#   bash scripts/cleanup_demo_artifacts.sh                # safe default
#   bash scripts/cleanup_demo_artifacts.sh --demo-data    # + truncate demo rows
#   bash scripts/cleanup_demo_artifacts.sh --all          # everything

set -uo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"
set -a; [ -f .env ] && . ./.env; set +a
ROOTPW="${MYSQL_ROOT_PASSWORD:-rootpass}"

DO_DEMO_DATA=0
DO_LOGS=0
DO_HA=0
for arg in "$@"; do
  case "$arg" in
    --demo-data)  DO_DEMO_DATA=1 ;;
    --logs)       DO_LOGS=1 ;;
    --ha)         DO_HA=1 ;;
    --all)        DO_DEMO_DATA=1; DO_LOGS=1; DO_HA=1 ;;
    --help|-h)
      # Print the leading comment block (stop at first non-# line).
      awk 'NR==1{next} /^[^#]/{exit} /^#/{sub(/^# ?/,""); print}' "$0"
      exit 0 ;;
    *) echo "Unknown flag: $arg (use --help)"; exit 2 ;;
  esac
done

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
ok()   { echo -e "  ${GREEN}✓${NC} $*"; }
warn() { echo -e "  ${YELLOW}!${NC} $*"; }
step() { echo -e "\n${CYAN}== $* ==${NC}"; }

# ── Always-on cleanup ────────────────────────────────────────────────────────────

step "1. Stop Flask demo if it's still running"
if pkill -f 'demo/app.py' 2>/dev/null; then
  ok "killed demo/app.py process(es)"
else
  ok "no Flask process running"
fi

step "2. Remove __pycache__ directories"
PYCACHE=$(find . -name '__pycache__' -type d -not -path './.git/*' 2>/dev/null | wc -l)
find . -name '__pycache__' -type d -not -path './.git/*' -exec rm -rf {} + 2>/dev/null
ok "removed $PYCACHE __pycache__ dir(s)"

# ── Optional: demo data ─────────────────────────────────────────────────────────

if [ "$DO_DEMO_DATA" = "1" ]; then
  step "3. Truncate demo rows from base MySQL (port 3307)"
  # secure_cards demo rows from phase4_encryption_test + phase7_chain_verify
  # (column is `holder`, holders look like 'phase4-demo' / 'phase7-chain-demo').
  DEL_SC=$(docker exec -i dbsec-mysql mysql -uroot -p"$ROOTPW" -N testdb \
    -e "DELETE FROM secure_cards WHERE holder LIKE 'phase%-demo'; SELECT ROW_COUNT();" \
    2>/dev/null | tail -1)
  ok "secure_cards: deleted ${DEL_SC:-0} demo row(s)"

  # orders R/W demo rows (only in base, the HA cluster has its own table state)
  DEL_OR=$(docker exec -i dbsec-mysql mysql -uroot -p"$ROOTPW" -N testdb 2>/dev/null \
    -e "DELETE FROM orders WHERE product LIKE 'rw-demo-%'; SELECT ROW_COUNT();" \
    2>/dev/null | tail -1)
  ok "orders: deleted ${DEL_OR:-0} R/W-demo row(s)"

  step "4. Clean HA cluster demo state (if cluster up)"
  if docker ps --format '{{.Names}}' | grep -q '^dbsec-mysql-1$'; then
    # ha_demo table (from failover demo) + demo users id<=5 + rw-demo orders in cluster
    docker exec -i dbsec-mysql-1 mysql -uroot -p"$ROOTPW" testdb 2>/dev/null <<'SQL' || true
DROP TABLE IF EXISTS ha_demo;
DELETE FROM orders WHERE product LIKE 'rw-demo-%';
DELETE FROM users WHERE id BETWEEN 1 AND 5 AND first_name='Demo' AND last_name='User';
SQL
    ok "HA cluster: dropped ha_demo + cleared rw-demo orders + demo users"
  else
    warn "HA cluster not running, skipped"
  fi
fi

# ── Optional: logs ───────────────────────────────────────────────────────────────

if [ "$DO_LOGS" = "1" ]; then
  step "5. Truncate MySQL logs + parsed audit artifacts"
  if [ -d logs/mysql ]; then
    SIZE_BEFORE=$(du -sh logs/mysql 2>/dev/null | cut -f1)
    # Truncate the rolling logs (MySQL keeps writing to the same inode).
    for f in logs/mysql/general.log logs/mysql/slow.log logs/mysql/error.log; do
      [ -f "$f" ] && truncate -s 0 "$f"
    done
    # Delete the parsed audit artifacts (regenerated by `make parse-audit`).
    rm -f logs/mysql/audit_report.json logs/mysql/audit_summary.csv
    # Tell MySQL to close + reopen its log fds so the OS actually releases the blocks
    # (without flush-logs, WSL2 bind-mount keeps showing the OLD allocation in du).
    if docker ps --format '{{.Names}}' | grep -q '^dbsec-mysql$'; then
      docker exec dbsec-mysql mysqladmin -uroot -p"$ROOTPW" flush-logs 2>/dev/null || true
    fi
    SIZE_AFTER=$(du -sh logs/mysql 2>/dev/null | cut -f1)
    ok "logs/mysql: ${SIZE_BEFORE:-?} -> ${SIZE_AFTER:-?}"
  else
    warn "logs/mysql does not exist, skipped"
  fi

  # Discovery + proxysql/acra session logs are small, but rotate them too.
  for d in logs/proxysql logs/acra logs/discovery; do
    if [ -d "$d" ]; then
      find "$d" -type f \( -name '*.log' -o -name '*.json' -o -name '*.csv' \) \
        -mtime +1 -delete 2>/dev/null || true
    fi
  done
  ok "rotated logs/proxysql logs/acra logs/discovery (files >1 day old)"
fi

# ── Optional: HA tear-down ──────────────────────────────────────────────────────

if [ "$DO_HA" = "1" ]; then
  step "6. Tear down the HA cluster (+ ha-router) — base stack untouched"
  if docker ps -a --format '{{.Names}}' | grep -qE '^dbsec-(mysql-[123]|ha-router)$'; then
    # Targeted container removal (NOT `docker compose down`, which would also stop
    # the base stack listed in compose.yaml). Mirrors scripts/phase7_ha_down.sh.
    docker rm -f dbsec-mysql-1 dbsec-mysql-2 dbsec-mysql-3 dbsec-ha-router 2>/dev/null \
      | sed 's/^/    removed: /' || true
    docker volume rm \
      database-security_mysql_ha_1_data \
      database-security_mysql_ha_2_data \
      database-security_mysql_ha_3_data 2>/dev/null \
      | sed 's/^/    volume removed: /' || true
    ok "HA containers + volumes gone (re-create with: make ha-bootstrap)"
  else
    warn "HA stack not up, skipped"
  fi
fi

# ── Summary ──────────────────────────────────────────────────────────────────────

echo
echo -e "${GREEN}Cleanup complete.${NC}"
echo "  flags used:"
echo "    demo-data=$DO_DEMO_DATA  logs=$DO_LOGS  ha=$DO_HA"
[ "$DO_DEMO_DATA" = "0" ] && echo "  (run with --demo-data to also delete demo rows)"
[ "$DO_LOGS" = "0" ]      && echo "  (run with --logs to truncate logs/mysql)"
[ "$DO_HA" = "0" ]        && echo "  (run with --ha to tear down the HA cluster)"
[ "$DO_DEMO_DATA$DO_LOGS$DO_HA" = "111" ] || echo "  (run with --all for everything)"
