#!/usr/bin/env bash
# Phase 7 - Bring the stack up in CHAINED mode:
#   Client -> ProxySQL (DBF) -> Acra (transparent encryption) -> MySQL
#
# This requires Acra to be running, which in turn requires ACRA_MASTER_KEY in .env
# (generated by scripts/phase4_acra_keys.sh). The script checks both.
#
# Run from the project root:
#   bash scripts/phase7_chain_up.sh

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

if [ ! -f .env ]; then
  echo "Missing .env. Create it with: cp .env.example .env" >&2
  exit 1
fi

if ! grep -q '^ACRA_MASTER_KEY=' .env; then
  echo "ACRA_MASTER_KEY not found in .env." >&2
  echo "Generate the keystore first: make acra-keys" >&2
  exit 1
fi

echo "== Bringing up stack in CHAINED mode (ProxySQL -> Acra -> MySQL) =="
# --profile acra pulls acra-server into the active project (it is profile-gated in
# the base compose.yaml). compose.chained.yaml swaps ProxySQL's config to the chained
# backend and waits for acra-server to be up.
docker compose -f compose.yaml -f compose.chained.yaml --profile acra up -d

echo
echo "== Waiting for ProxySQL admin (6032) to accept connections =="
# ProxySQL takes a few seconds after start before the admin interface is listening.
# Without this, the rule loader below races the daemon and fails on connection refused.
for i in $(seq 1 30); do
  if docker exec dbsec-mysql mysql --ssl-mode=DISABLED -h dbsec-proxysql -P 6032 \
       -uradmin -pradmin -e "SELECT 1" >/dev/null 2>&1; then
    echo "  ready after ${i}s"
    break
  fi
  sleep 1
done

echo
echo "== Loading DBF deny rules into ProxySQL =="
# The deny rules still live at the ProxySQL layer; Phase 4's loader works unchanged.
bash scripts/phase4_proxysql_setup.sh >/dev/null

echo
echo "== Verifying ProxySQL backend points at Acra =="
docker exec dbsec-mysql mysql --ssl-mode=DISABLED -h dbsec-proxysql -P 6032 \
  -uradmin -pradmin -t 2>/dev/null \
  -e "SELECT hostgroup_id, hostname, port FROM runtime_mysql_servers;"

echo
echo "Chained mode is active. Validate with:"
echo "  python3 scripts/phase7_chain_verify.py"
echo
echo "Revert to default (ProxySQL -> MySQL):"
echo "  bash scripts/phase7_chain_down.sh"
